name: Context variable Dempo
on: push
jobs:
  contect-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use Context Variables
        run: |
          echo "this eorkflow is triggered by ${{ github.actor }}"
          echo "The repository name is ${{ github.repository }}"

      - name: Print all variables under github
        run: echo "${{ toJson(github) }} "
      
