name: Hello World
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "This is a Demo Build."
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test Step
        run: echo "This is a Demo Test."
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      -  name: Deploy Step
         run: echo "This is a Demo Deploy."
      
  
