name: Hello World
on: workflow_dispatch
jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: |
          echo "Welcome 1"
          echo "Welcome 2"
          echo "Welcome 3"

        
