name: Nice if example
on:
    push:
        branches:
            - main
            - develop
            - feature/**
jobs:
    quality_checks:
        if: startsWith(github.ref_name, 'feature') && github.ref_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: perform quality checks
              run: echo "Performing quality checks on the code"

    dev-deploy:
        if: github.ref_name == 'develop' && github.ref_name == 'push'        
        runs-on: ubuntu-latest
        steps:        
            - name: development deploy
              run: echo "deploying the code to development environment"
            
    prod-deploy:
        if: github.ref_name == 'main' && github.ref_name == 'push'        
        runs-on: ubuntu-latest
        steps:        
            - name: production deploy
              run: echo "deploying the code to production environment"     
        
    success_notification:
        needs: ['quality_checks', 'dev-deploy', 'prod-deploy']
        if: always() && !failure()       
        runs-on: ubuntu-latest
        steps:        
            - name: notify success
              run: echo "Success email sent to the team"     
              
    failure_notification:
        needs: ['quality_checks', 'dev-deploy', 'prod-deploy']
        if: failure()       
        runs-on: ubuntu-latest
        steps:        
            - name: notify failure
              run: echo "Failure email sent to the team"
   