name: Output Demo
on: push
jobs:
  build:
    outputs:
      version: ${{steps.step1.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Step One  
        id: step1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
      - name: Step Two
        run: echo "This version is ${{ steps.step1.outputs.version }}"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy the app
        run: echo "We are deploying the app with version ${{ needs.build.outputs.version }}"  
  
        
